setup:
  seed: 2
  use_gpu: False

train:
  name: 'TurtleBot3'
  n_episodes: 5001
  verbose: 250

agent:
  update_start: 1  # n° episodes before the network updates start
  polyak: True
  tg_update: 5

  gamma: 0.99
  tau: 0.005

  eps: 1
  eps_min: 0.05
  eps_d: 0.99

  buffer:
    size: 20000 
    batch: 128

  dnn:
    h_layers: 2
    h_size: 64
    print_model: False


  
      

